# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVN-Statistics
version:      0.018
version_from: Statistics.pm
installdirs:  site
requires:
    RRDTool:OO:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
